/**
 * lib/api/types.ts — TypeScript types for the Predict public server.
 *
 * Generated by hitting the LIVE testnet server (predict-testnet-4-16) on
 * 2026-06-03 and modelling the actual JSON. Scaling notes inline:
 *   - `@1e9`  = FLOAT_SCALING integer (use config/scale toFloat).
 *   - `@6dec` = DUSDC base units      (use config/scale fromQuote).
 *   - plain   = unscaled (timestamps ms, checkpoints, counts, ratios already float).
 *
 * VERIFY-FIRST status: schemas below are confirmed against live responses for
 * /status, /predicts/:id/state, /predicts/:id/oracles, /oracles/:id/state,
 * /oracles/:id/svi/latest, /oracles/:id/prices/latest, /predicts/:id/vault/summary,
 * /predicts/:id/quote-assets. Manager/positions/history shapes are filled in Phase 1.
 */

/* ----------------------------- /status ----------------------------- */

export interface PipelineStatus {
  pipeline: string;
  checkpoint_hi_inclusive: number;
  timestamp_ms_hi_inclusive: number;
  epoch_hi_inclusive: number;
  checkpoint_lag: number;
  time_lag_ms: number;
  time_lag_seconds: number;
  latest_onchain_checkpoint: number;
  is_backfill: boolean;
}

export interface StatusResponse {
  status: string; // "OK"
  latest_onchain_checkpoint: number;
  current_time_ms: number;
  earliest_checkpoint: number;
  max_lag_pipeline: string;
  max_checkpoint_lag: number;
  max_time_lag_seconds: number;
  pipelines: PipelineStatus[];
}

/* --------------------- /predicts/:id/state ------------------------- */

// pricing/risk return null until configured; shapes TBD from source (config reads §5.1).
export interface PredictState {
  predict_id: string;
  pricing: PricingConfig | null;
  risk: RiskConfig | null;
  trading_paused: boolean | null;
  quote_assets: string[]; // fully-qualified coin types (without 0x prefix on testnet)
}

// Placeholder — populate when the server starts returning non-null config,
// or read directly on-chain (base_spread, min_spread, utilization_multiplier, ...).
export interface PricingConfig {
  base_spread?: number;
  min_spread?: number;
  utilization_multiplier?: number;
  [k: string]: unknown;
}

export interface RiskConfig {
  max_total_exposure_pct?: number;
  [k: string]: unknown;
}

/* --------------------- oracles & oracle state ---------------------- */

export type OracleStatus = 'active' | 'settled' | 'pending' | string;

export interface Oracle {
  predict_id: string;
  oracle_id: string;
  oracle_cap_id: string;
  underlying_asset: string; // "BTC"
  expiry: number; // ms epoch
  min_strike: number; // @1e9
  tick_size: number; // @1e9 — NOTE: tick COUNT not in this payload (VERIFY §6.3 from source)
  status: OracleStatus;
  activated_at: number; // ms epoch
  settlement_price: number | null; // @1e9
  settled_at: number | null; // ms epoch
  created_checkpoint: number;
}

/** Common envelope fields on every event-sourced row from the server. */
export interface EventEnvelope {
  event_digest: string;
  digest: string;
  sender: string;
  checkpoint: number;
  checkpoint_timestamp_ms: number;
  tx_index: number;
  event_index: number;
  package: string;
  oracle_id: string;
  onchain_timestamp: number; // ms epoch
}

/** OraclePricesUpdated — spot/forward tape (~1s). */
export interface PriceEvent extends EventEnvelope {
  spot: number; // @1e9
  forward: number; // @1e9
}

/**
 * OracleSVIUpdated — drives the surface & time-travel scrub.
 * Signed-magnitude encoding: rho/m carry a separate `*_negative` boolean.
 * Use config/scale signedToFloat(rho, rho_negative).
 */
export interface SviEvent extends EventEnvelope {
  a: number; // @1e9, >= 0
  b: number; // @1e9, >= 0
  rho: number; // @1e9 magnitude
  rho_negative: boolean;
  m: number; // @1e9 magnitude
  m_negative: boolean;
  sigma: number; // @1e9, >= 0
}

export interface AskBounds {
  min: number; // @1e9
  max: number; // @1e9
  [k: string]: unknown;
}

export interface OracleStateResponse {
  oracle: Oracle;
  latest_price: PriceEvent | null;
  latest_svi: SviEvent | null;
  ask_bounds: AskBounds | null;
}

/* ------------------------- vault summary --------------------------- */

/* ----------------------- managers & positions ---------------------- */

/** Row from /managers (PredictManagerCreated event). */
export interface ManagerRow extends Omit<EventEnvelope, 'oracle_id'> {
  manager_id: string;
  owner: string;
}

export interface ManagerBalance {
  quote_asset: string;
  balance: number; // @6dec
}

/** /managers/:id/summary */
export interface ManagerSummary {
  manager_id: string;
  owner: string;
  balances: ManagerBalance[];
  trading_balance: number; // @6dec — free DUSDC in the manager
  open_exposure: number; // @6dec
  redeemable_value: number; // @6dec
  realized_pnl: number; // @6dec signed
  unrealized_pnl: number; // @6dec signed
  account_value: number; // @6dec
  open_positions: number; // count
  awaiting_settlement_positions: number; // count
}

export type PositionStatus = 'open' | 'redeemed' | 'settled' | 'awaiting_settlement' | string;

/** Row from /managers/:id/positions/summary */
export interface PositionSummary {
  predict_id: string;
  manager_id: string;
  quote_asset: string;
  oracle_id: string;
  underlying_asset: string;
  expiry: number; // ms
  strike: number; // @1e9
  is_up: boolean;
  minted_quantity: number; // @6dec
  redeemed_quantity: number; // @6dec
  open_quantity: number; // @6dec
  total_cost: number; // @6dec
  total_payout: number; // @6dec
  realized_pnl: number; // @6dec signed
  unrealized_pnl: number; // @6dec signed
  open_cost_basis: number; // @6dec
  average_entry_price: number; // @1e9 (per-unit ask)
  average_exit_price: number; // @1e9
  mark_price: number | null; // @1e9
  mark_value: number | null; // @6dec
  status: PositionStatus;
  first_minted_at: number; // ms
  last_activity_at: number; // ms
}

/** /managers/:id/pnl */
export interface ManagerPnl {
  manager_id: string;
  range: string;
  series_type: string;
  points: { timestamp_ms?: number; value?: number }[];
  current_unrealized_pnl: number; // @6dec
  current_total_pnl: number; // @6dec
}

/* --------------------- vault performance & events ------------------ */

export interface VaultPerformancePoint {
  timestamp_ms: number;
  share_price: number; // float
  vault_value: number; // @6dec
  total_shares: number; // @6dec (PLP)
}

export interface VaultPerformance {
  predict_id: string;
  range: string;
  points: VaultPerformancePoint[];
}

/** /positions/minted row (PositionMinted event). */
export interface PositionMintedEvent extends EventEnvelope {
  predict_id: string;
  manager_id: string;
  trader: string;
  quote_asset: string;
  expiry: number;
  strike: number; // @1e9
  is_up: boolean;
  quantity: number; // @6dec
  cost: number; // @6dec
  ask_price: number; // @1e9
}

/** /positions/redeemed row (PositionRedeemed event). */
export interface PositionRedeemedEvent extends EventEnvelope {
  predict_id: string;
  manager_id: string;
  owner: string; // manager owner (the trader credited the payout)
  executor: string; // who submitted the redeem (== owner unless permissionless)
  quote_asset: string;
  expiry: number;
  strike: number; // @1e9
  is_up: boolean;
  quantity: number; // @6dec
  payout: number; // @6dec
  bid_price: number; // @1e9
  is_settled: boolean;
}

export interface VaultSummary {
  predict_id: string;
  quote_assets: string[];
  vault_balance: number; // @6dec
  vault_value: number; // @6dec
  total_mtm: number; // @6dec
  total_max_payout: number; // @6dec
  available_liquidity: number; // @6dec
  available_withdrawal: number; // @6dec
  plp_total_supply: number; // @6dec (PLP supply)
  plp_share_price: number; // float ratio
  utilization: number; // float 0..1
  max_payout_utilization: number; // float 0..1
  net_deposits: number; // @6dec
  total_supplied: number; // @6dec
  total_withdrawn: number; // @6dec
}
